### PR TITLE
Add Macedonia

### PR DESCRIPTION
**Pull request by srdjanRakic**
### Overview

Add Macedonia.

### CODE REVIEW

**Comment by srdjanRakic** [comment]
Sorry for prettifying, I can undo it. Let me know.

**Comment by gayanvoice** [comment]
Thank you @srdjanRakic I need some time to review the code. I will add it to the servers.

**Comment by srdjanRakic** [comment]
Hey @gayanvoice, 

Thank you for the swift response, if you need help maitaing the repo let me know.

Kind Regards,
Srdjan

**Comment by gayanvoice** [comment]
Awesome @srdjanRakic You can suggest changes for the UI which is based on React. You can run it by cloning the project and go to `cd client` and `npm run start` and I know it needs some kind of improvements. The server and the client is completely isolated. So you can  run the client separately.

**Pull request merged**
